os:
  - linux

sudo: required
dist: trusty

services:
- docker

# safelist
branches:
  only:
    - brewmaster

env:
    - CONFIG="Default" SCRIPT="configure-repos-tests.sh" CI_DOCKER_IMAGE=professorkaos64/steamos ARCH=i386

# Pull containers from Docker Hub.
before_install:
  - docker pull $CI_DOCKER_IMAGE

script:
  - cd "$TRAVIS_BUILD_DIR"

# Start the container from the image and perform tests.
# linux32 will correct any false reporting of non-32bit.
script:
  - "docker run -i -v \"${PWD}:/steamos-tools\" $CI_DOCKER_IMAGE /bin/bash -c \"linux32 --32bit $ARCH /steamos-tools/travis/$SCRIPT\""

# Email on failure only
notifications:
  email:
    on_success: never
    on_failure: never
