os:
	- linux

sudo: required
dist: trusty

# blocklist
#branches:
#	except:
#		- master

# safelist
branches:
  only:
  - brewmaster

#install:

# Test configuring repositories and different scenarios around it
# This tests basic repo configuration, repo availability, and syntax errors
# If something goes wrong with a repo push, this should show an alert.

# Other tests will be added later on, but this is the main important one

script:
	- cd "$TRAVIS_BUILD_DIR"
	- ./configure-repos.sh && ./configure-repos.sh --remove
	- ./configure-repos.sh && ./configure-repos.sh --remove-testing
	- ./configure-repos.sh --default && ./configure-repos.sh --remove
	- ./configure-repos.sh --repair && ./configure-repos.sh --remove
	- ./configure-repos.sh --enable-testing && ./configure-repos.sh --remove

# Email on failure only

notifications:
	email:
    	on_success: never
    	on_failure: always
