os:
  - linux

sudo: required
dist: trusty

services:
- docker

# safelist
branches:
  only:
    - brewmaster

env:
    - CONFIG="Repo tests" SCRIPT="configure-repos-test.sh" CI_DOCKER_IMAGE=professorkaos64/steamos ARCH=i386
    - CONFIG="Package tests" SCRIPT="package-tests.sh" CI_DOCKER_IMAGE=professorkaos64/steamos ARCH=i386

# Pull containers from Docker Hub.
before_install:
  - docker pull $CI_DOCKER_IMAGE

script:
  - cd "$TRAVIS_BUILD_DIR"

# Start the container from the image and perform tests.
# linux32 will correct any false reporting of non-32bit.
# Note: The below command clones the source into the specified folder, but the command passed
# will start in /, so be sure to cd into "steamos-tools" in test scripts.
script:
  - "docker run -i -v \"${PWD}:/steamos-tools\" $CI_DOCKER_IMAGE /bin/bash -c \"/steamos-tools/travis/$SCRIPT\""

# Email on failure only
notifications:
  email:
    on_success: never
    on_failure: never
